---
- name: Configure system
  hosts: mini
  vars_files:
    - vars/public.yml
    - vars/vault.yml
  roles:
    - role: system
    - role: exploide.dnf-automatic
      become: true
    - role: disks
    - role: artis3n.tailscale.device
    - role: reverse_proxy
    - role: backups
    - role: admin
    - role: notifications
    - role: media
  tasks:
    - name: Add podman cleanup job
      become: true
      ansible.builtin.cron:
        name: Cleanup dangling podman extras
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "0"
        job: podman volume prune -f &> /dev/null && podman image prune -af &> /dev/null
    - name: Add podman cleanup job (user)
      become: false
      ansible.builtin.cron:
        name: Cleanup dangling podman extras
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "0"
        job: podman volume prune -f &> /dev/null && podman image prune -af &> /dev/null
